### ISSUE TITLE
Préciser la (les) licence(s) 

### ISSUE THREAD

**Issue by bzg** [DISIC/greentech#12]
Bonjour, le README indique que le dépôt est placé sous licence Ouverte 2.0.

Cette licence est adaptée aux *données* (en open data) ou aux *documents administratifs classiques* plutôt qu'aux codes sources.

Vu que le dépôt propose à la fois des codes sources (tout ce qui n'est pas `.md`) et des données (`*.md`), je propose que le `README` indique:

```
Les codes sources de ce dépôt sont placés sous licence MIT.

Les contenus humainement lisibles sont placés sous licence Ouverte 2.0.
```

L'avantage d'utiliser la licence MIT ici est que c'est la même que celle du projet [eleventy](https://github.com/11ty/eleventy/blob/master/LICENSE) (dont j'imagine qu'on retrouve une partie du code) et que celle du *design system* de l'Etat.

En plus des deux phrases ci-dessus, une précision sur la Marianne peut être utile, comme on le fait [dans ce dépôt](https://github.com/etalab/bulma-theme-gouv-fr#licence).

Si vous voulez que je fasse une PR, n'hésitez pas !

**Comment by supertanuki** [comment]
Merci !
Corrigé par la PR #14

**Comment by bzg** [comment]
Merci !
