### ISSUE TITLE
orthotypographie

### ISSUE THREAD

**Issue by Erwan-le-Gall** [DISIC/greentech#2]
Bonjour,

J’ai utilisé : https://addons.mozilla.org/fr/firefox/addon/grammalecte-fr/

https://github.com/DISIC/greentech/blob/main/_includes/layouts/base.njk#L133
pied de page : Ministère de la Transition Ecologique. -> Écologique

https://github.com/DISIC/greentech/blob/main/r%C3%A9glementations/index.md#services-publiques-%C3%A9coresponsables
Services publiques -> publics
mesure 8 : […] visio-conférence -> visioconférence

https://github.com/DISIC/greentech/blob/main/r%C3%A9glementations/index.md#les-r%C3%A9glementations-existantes-en-france
L’obsolescence programmée a été défini en 2015 -> définie

https://github.com/DISIC/greentech/blob/main/r%C3%A9glementations/index.md#au-niveau-europ%C3%A9en-
Au niveau Européen -> européen

https://github.com/DISIC/greentech/blob/main/publications/guide-pratique-achats-numeriques-responsables/introduction.md#quelles-sont-les-parties-prenantes-de-ce-guide-
un outil gratuit accessibles à -> accessible à

https://github.com/DISIC/greentech/blob/main/publications/guide-pratique-achats-numeriques-responsables/equipe-projet.md
Remerciement particuliers -> Remerciements particuliers 

BCdt,
R1

**Comment by supertanuki** [comment]
Merci @Erwan-le-Gall je corrige

**Comment by Erwan-le-Gall** [comment]
elle est au SILL :)
https://sill.etalab.gouv.fr/fr/software?q=grammalecte&year=2021

**Comment by supertanuki** [comment]
C'est corrigé, merci https://github.com/DISIC/greentech/commit/f80dde143c66e88cf3aba23553154d2747888a1b
