### ISSUE TITLE
Alternative à une image

### ISSUE THREAD

**Issue by benoitdequick** [DISIC/greentech#4]
Hello, 
Sur la page L’analyse de cycle de vie (http://ecoresponsable.numerique.gouv.fr/publications/guide-pratique-achats-numeriques-responsables/demarche-numerique-responsable/analyse-cycle-de-vie/), on trouve une image dont l'attribut alt="Schéma d'un cycle de vie". Cet élément n'est pas une alternative pertinente à l'image.

Vu la complexité de l'image, il faudrait que l'alternative soit vide (alt="") et que le contenu du schéma soit retranscrit intégralement dans le texte ou en mettant en place une description détaillée, exhaustive et adjacente à l'image (avec un collapse par exemple).

**Comment by supertanuki** [comment]
Merci pour ta vigilance ! J'ai supprimé le contenu du alt, car la description de l'ACV est le contenu de la page, donc inutile de doublonner en décrivant l'image.
